### ISSUE TITLE
Scaling Peers?

### ISSUE THREAD

**Issue by bslayton** [KeithErmel/MultipeerKit#1]
@KeithErmel Assuming that you haven't tested this code in large scale environments, do you have any theories as to how it might perform? Looks like your code automatically connects to peers. Do you think this would scale in a similar fashion as firechat to thousands of peers?

**Comment by KeithErmel** [comment]
I've only used this code for prototyping purposes so far, connecting only around a half-dozen nearby devices with a relatively small amount of data passing between them. Scaling up to thousands of peers would be problematic, I'd imagine.
